### ISSUE TITLE
add a strokeWidth parameter maybe more flexible

### ISSUE THREAD

**Issue by lovebzhou** [FlorinMihalache/flutter_progress_hud#1]
Widget _buildDefaultIndicator() {
    return Container(
      width: 40.0,
      height: 40.0,
      child: CircularProgressIndicator(
        strokeWidth: 3.0,  // add a config parameter here
        valueColor: AlwaysStoppedAnimation(widget.indicatorColor),
      ),
    );
  }

Thanks

**Comment by FlorinMihalache** [comment]
That's a great idea, I just published an update which includes `borderColor` and `borderWidth`. Thank you :-).
