### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by burhanaksendir** [FlorinMihalache/flutter_progress_hud#10]
Scenario:
progress?.show(); after it runs, if the user leaves the scene with the back key without waiting for the animation, the following error occurs: Unhandled Exception: setState() called after dispose():

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _ProgressHUDState#66b21(lifecycle state: defunct, not mounted, ticker inactive)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter<…>`

**Comment by nikunjkhunt-easternts** [comment]
@burhanaksendir  have you find any solution to this ?
@FlorinMihalache ???

**Comment by burhanaksendir** [comment]
> @burhanaksendir have you find any solution to this ?
> @FlorinMihalache ???

Yes. I created a PR that fixed the problem:
https://github.com/FlorinMihalache/flutter_progress_hud/pull/11/commits/766b1dfb49b10bca9c586c55e5c50cbd30f81b00

**Comment by FlorinMihalache** [comment]
I just merged the PR, thank you @burhanaksendir :)
