### ISSUE TITLE
Wrap MaterialApp

### ISSUE THREAD

**Issue by jasonlaw** [FlorinMihalache/flutter_progress_hud#2]
Hi @FlorinMihalache ,

Can we wrap with the MaterialApp so that we can refer to it in all widget?
Do you foresee any issue with this?

Thanks in advance.

**Comment by FlorinMihalache** [comment]
Hi @jasonlaw ,

In theory I think you can, but I didn't test this, not sure if this could cause issues. I'm still a newbie with Flutter :-).
