### ISSUE TITLE
This is a nice package but doesn't seem to work for modal barrier

### ISSUE THREAD

**Issue by jagan999** [FlorinMihalache/flutter_progress_hud#3]
I used the package as is mentioned in the example. It shows me the circular progress indicator but if I tap elsewhere in the page, it dismisses the progress indicator. According to the documentaiton, default is modal barrier = true, so it should be modal but it appears not.

**Comment by jagan999** [comment]
I played around. Looks like setting the barrierEnabled to false works properly. Maybe change the property name?

**Comment by FlorinMihalache** [comment]
Hello @jagan999,

First of all, thank you for the feedback. I just tried what you said on the example project and it works as intended, the barrier is enabled by default and blocks touches on all children widgets of `ProgressHUD`.

Could you please show me an example code that doesn't work as planned?

**Comment by jagan999** [comment]
Hello
As indicated in my next comment, when I set barrierEnabled to false, it worked as expected. I don't know why. It's too painful for me to extract my app code for you to test.
Jagan
    On Monday, July 29, 2019, 01:27:45 PM GMT+5:30, Florin Mihalache <notifications@github.com> wrote:  
 
 
Hello @jagan999,

First of all, thank you for the feedback. I just tried what you said on the example project and it works as intended, the barrier is enabled by default and blocks touches on all children widgets of ProgressHUD.

Could you please show me an example code that doesn't work as planned?

**Comment by bdangvnt** [comment]
barrierEnabled = false but when tap, but I don't know why naviator auto pop to previous page widget?
