### ISSUE TITLE
If i tap while loading, the app go back

### ISSUE THREAD

**Issue by christianarduino** [FlorinMihalache/flutter_progress_hud#5]
If the ProgressHUD widget is showing the circular progress indicator, when I tap on it, the app go back

**Comment by Jaimin9998** [comment]
i am also facing the same issue. is there any solution of this?

**Comment by tamhv** [comment]
me too

**Comment by franciscrispin** [comment]
https://github.com/FlorinMihalache/flutter_progress_hud/pull/9 should fix this issue.

**Comment by glintpursuit** [comment]
I am facing this issue for current version   flutter_progress_hud: ^2.0.0

screen is dismissed when click on ProgressBar.

**Comment by glintpursuit** [comment]
@tamhv 

How did you fix it?

**Comment by tamhv** [comment]
@glintpursuit pls try `dismissible: false` for `ModalBarrier`

```
@override
Widget build(BuildContext context) {
    final children = <Widget>[];
    if (widget.barrierEnabled) {
      children.add(
        Visibility(
          visible: _barrierVisible,
          child: ModalBarrier(
            dismissible: false,
            color: widget.barrierColor,
          ),
        ),
      );
    }
   ...
}
```

**Comment by glintpursuit** [comment]
Thanks for quick response @tamhv 

This change will be in package file right ?

**Comment by tamhv** [comment]
yeah this file
https://github.com/FlorinMihalache/flutter_progress_hud/blob/b70381b92229c8a1c1d36c71ba73524fd313297d/lib/flutter_progress_hud.dart#L116

**Comment by glintpursuit** [comment]
Thanks @tamhv 

I am wondering how to take care of this change in Build process (CI/CD)

**Comment by tamhv** [comment]
@glintpursuit you need to fork this repo, edit and commit your customize code, add your fork to pubspec.yaml
```
dependencies:
  widget:
    git: git@github.com:blabla/flutter_progress_hud.git
```

or you can download file flutter_progress_hud.dart to your project, edit and use it directly in your project

**Comment by glintpursuit** [comment]
Cool. 

If I don't get better modal progress bar (till now no) then I will add this file to my project. 

Thanks for all help @tamhv
