### ISSUE TITLE
The click event is blocked by loading and cannot be triggered

### ISSUE THREAD

**Issue by sdaduanbilei** [FlorinMihalache/flutter_progress_hud#7]
When the show method is not called, the click event is blocked and the click cannot be triggered
![](https://gitee.com/sdaduanbilei/images/raw/master/img/20210106152146.png)

**Comment by sdaduanbilei** [comment]
As shown in the figure, the red box is just the position of loading display. When you click the red position, you cannot trigger the event in the lower time selection bar

**Comment by FlorinMihalache** [comment]
Hi, this issue was fixed in the latest version (1.0.3). Please give it a try, I released it yesterday.

**Comment by sdaduanbilei** [comment]
Ouligoi
