### ISSUE TITLE
Why do I get double underlines when I use showWithText()

### ISSUE THREAD

**Issue by hy-net** [FlorinMihalache/flutter_progress_hud#8]
![image](https://user-images.githubusercontent.com/55421612/124482048-7b3b6b00-dddb-11eb-9f3c-7eee77bb6779.png)

**Comment by yaizudamashii** [comment]
In your ProgressHUD widget, you have to add an attribute
`textStyle: TextStyle(color: Colors.white, fontSize: 14.0, decoration: TextDecoration.none),`

**Comment by tommyle** [comment]
Wrap `ProgressHud` with `Material` widget.

```
Material(
      child: ProgressHUD(
```
